server:
  port: 8081
  servlet:
    context-path: /tour_boot
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    view:
      prefix: /
      suffix: .jsp
  banner:
    location: classpath:/banner.txt
    charset: UTF-8
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:mapper/*Mapper.xml

